[
  {
    Name: "MAHNOOR ARSHAD",
    Education: [
      "BSCS, 7th Semester, CGPA: 3.30, UET (Main Campus), 2021 to Present",
      "FSc. Pre Engineering, Punjab Group Of Colleges, 2019 to 2021",
    ],
    Experience: [
      "Full-Stack Development Intern at Ustadam: Developed a web application for children’s moral development using MEAN stack and agile methodologies (2023).",
    ],
    Skills: [
      "Java",
      "C++",
      "Python",
      "ReactJS",
      "HTML",
      "CSS",
      "JavaScript",
      "Spring Framework",
      "C#",
      "ASP.NET",
      "Node.js",
      "MongoDB",
      "Angular",
      "WPF .NET",
      "SQL",
      "Git",
      "OpenCV",
      "PostgreSQL",
      "MySQL",
      "Object-Oriented Design",
      "Agile Methodologies",
      "Software Architecture",
      "System Design",
      "Technical Writing",
      "Code Optimization",
      "Efficient Debugging",
      "Team Leadership",
    ],
    Projects: [
      "E-Learning Desktop App (C++, .NET)",
      "Game Framework & Game (C++)",
      "C++ Compiler (Built in C++)",
      "Loan Management System (WPF .NET Framework, C++)",
      "Real Estate Scraper (Selenium, Zameen.com data, DSA algorithms)",
      "Information Retrieval Systems (BM25, Proximal Nodes, GVSM, LSI)",
      "Plagiarism Detector (OCR, TF-IDF, Cosine Similarity)",
      "Point of Sale System",
      "E-commerce Web App (ReactJS, Node.js, MongoDB)",
      "Home Office Network Design (Computer Networks)",
    ],
    Profile:
      "Aspiring Software Engineer with expertise in software architecture, design, development, and technical writing.  Experienced in team leadership and quick adaptation to new technologies.",
    Phone: "03114412825",
    Languages: [],
    Certifications: [
      "Machine Learning Specialization, Stanford University, Feb 2024",
      "Advanced Learning Algorithms, Stanford University, Jan 2024",
      "React Basics, Meta, Feb 2024",
      "Advanced React, Meta, Jan 2024",
      "HTML and CSS in Depth, Meta, Jan 2024",
      "Introduction to Front-End Development, Meta, Dec 2023",
      "Programming for Everybody, University of Michigan, Oct 2023",
    ],
    Interests: [],
    Address: "",
    Email: "mahnoorarshad311002@gmail.com",
    LinkedIn: "",
    GitHub: "github.com/MahnoorArshad71",
    "Other Links": [],
  },
];
